force-app/main/default/objects/Account/fields/DataContract__c.field-meta.xml
<CustomField>
    <fullName>DataContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Contract</label>
    <referenceTo>DataContract__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DataContract__c/DataContract__c.object-meta.xml
<CustomObject>
    <label>Data Contract</label>
    <nameField>
        <label>Data Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DataContract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DataContract__c/fields/Encrypt__c.field-meta.xml
<CustomField>
    <fullName>Encrypt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Encrypt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DataEncryptionQueueSettings__c/DataEncryptionQueueSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Data Encryption Queue Settings</label>
</CustomObject>

force-app/main/default/objects/DataEncryptionQueueSettings__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EncryptedDocument__c/EncryptedDocument__c.object-meta.xml
<CustomObject>
    <label>Encrypted Document</label>
    <nameField>
        <label>Encrypted Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encrypted Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EncryptedDocument__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Encrypted Documents</relationshipLabel>
    <relationshipName>EncryptedDocuments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DataEncryptionQueueable.cls
public without sharing class DataEncryptionQueueable implements queueable{  
    
    private static DataEncryptionQueueSettings__c settings = DataEncryptionQueueSettings__c.getOrgDefaults();
    
    public void execute(QueueableContext context){
        // Abort process if disabled in custom settings - provides an out in cases of infinite queuable loop
        if(!settings.Enabled__c) return;
        
        Integer batchSize = Integer.valueOf(settings.BatchSize__c);
        
        // Needed for later to determine if another Queue needs to be chained
        Integer numberContactsNeedProcessed = (Integer)[SELECT Count(Id) FROM Contact WHERE Account.DataContract__r.Encrypt__c = true
        AND Id NOT IN (SELECT Contact__c FROM EncryptedDocument__c)][0].get('expr0');
        
        List<Contact> contactsToProcess = [SELECT Id FROM Contact WHERE Account.DataContract__r.Encrypt__c = true
            AND Id NOT IN (SELECT Contact__c FROM EncryptedDocument__c) LIMIT :batchSize];
        
        Set<Id> contactIdsToProcess = new Set<Id>();
        for(Contact c: contactsToProcess){
            contactIdsToProcess.add(c.Id);
        }

        try {
            //Downloads documents from an API, encrypts them, and stores them under the contact as EncryptedDocument__c records
            DataEncrypter dataEncrypter = new DataEncrypter(contactIdsToProcess);
            dataEncrypter.start();
        } catch(Exception error) {
            System.debug('DataEncryptionQueueable.execute() failed for contacts with id: ' + contactIdsToProcess 
                + '\nJob Id: ' + context.getJobId());
        }

        if(numberContactsNeedProcessed > batchSize && (Limits.getLimitQueueableJobs() - Limits.getQueueableJobs() > 0)){
            try {
                enqueueNewJob(context.getJobId());
            } catch(Exception error) {
                retryQueueInFuture(context.getJobId(), batchSize, numberContactsNeedProcessed);
            }
        }
    }

    public static void enqueueNewJob(Id currentJobId){
        List<AsyncApexJob> jobs = [SELECT Id, Status, ExtendedStatus FROM AsyncApexJob WHERE JobType = 'Queueable' 
            AND (Status = 'Queued' OR Status = 'Holding')
            AND ApexClass.Name = 'DataEncryptionQueueable' AND Id != :currentJobId LIMIT 1];

        if(jobs.size() == 0){
            System.enqueueJob(new DataEncryptionQueueable());
        }
    }

    @future
    private static void retryQueueInFuture(Id currentJobId, Integer batchSize, Integer numberContactsNeedProcessed){
        if(!settings.Enabled__c) return;
        try {
            if(Limits.getLimitQueueableJobs() - Limits.getQueueableJobs() > 0){
                enqueueNewJob(currentJobId);
            }
        } catch(Exception error) {
            System.debug('DataEncryptionQueueable.retryQueueInFuture() failed to queue'
                + '\nJob Id: ' + currentJobId 
                + '\nBatch size ' + batchSize 
                + '\nNumber of contacts that need processed: ' + numberContactsNeedProcessed);
        }
    }
}