force-app/main/default/objects/EncryptedDocument__c/EncryptedDocument__c.object-meta.xml
<CustomObject>
    <label>Encrypted Document</label>
    <nameField>
        <label>Encrypted Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encrypted Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EncryptedDocument__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Encrypted Documents</relationshipLabel>
    <relationshipName>EncryptedDocuments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DataEncrypter.cls
public with sharing class DataEncrypter {
    private Boolean THROW_ERROR = false;
    private Set<Id> contactIdsToProcess;

    public DataEncrypter(Set<Id> contactIdsToProcess) {
        this.contactIdsToProcess = contactIdsToProcess;
    }

    public void start() {
        if(!THROW_ERROR)
        {
            List<EncryptedDocument__c> newEncryptedDocuments = new List<EncryptedDocument__c>();
            for(Id contactId: contactIdsToProcess) {
                Integer randomNumber = Integer.valueof((Math.random() * 10)) + 1;
                for(Integer i = 0; i < randomNumber; i++){
                    newEncryptedDocuments.add(new EncryptedDocument__c(Contact__c = contactId));
                }
            }
            insert newEncryptedDocuments;
        } else {
            for(Integer i = 0; i < 201; i++) {
                List<Account> accounts = [SELECT Name FROM Account LIMIT 1];
            }
        }
    }
}